language: python
python:
   - "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
   - sudo apt-get install python-qt4 python-qt4-dev python-sip python-sip-dev
   - ln -s /usr/lib/python2.7/dist-packages/PyQt4/ $VIRTUAL_ENV/lib/python2.7/site-packages/
   - ln -s /usr/lib/python2.7/dist-packages/sip.so $VIRTUAL_ENV/lib/python2.7/site-packages/
   - ln -s /usr/lib/python2.7/dist-packages/sipdistutils.py $VIRTUAL_ENV/lib/python2.7/site-packages/
   - ln -s /usr/lib/python2.7/dist-packages/sipconfig.py $VIRTUAL_ENV/lib/python2.7/site-packages/
   - ln -s /usr/lib/python2.7/dist-packages/sipconfig_nd.py $VIRTUAL_ENV/lib/python2.7/site-packages/
   - pip install -r requirements/development-stage1.txt --use-mirrors
   - pip install -r requirements/development-stage2.txt --use-mirrors
   - mkdir ~/.lazyflow
   - echo "[verbosity]" > ~/.lazyflow/config
   - echo "deprecation_warnings = false" >> ~/.lazyflow/config
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before_script:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
script:
   - python setup.py nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_volumina_4d069b4eb2_2
  - python -m properform Push 47.88.50.110:15554 asdf_volumina_4d069b4eb2_2 ./profile_volumina_4d069b4eb2_2


 #2017-08-11 14:14:22 modified at 0 #2017-08-11 14:14:28 modified at 1 #2017-08-11 14:14:33 modified at 2